from snakemake.utils import validate

# Validate config-file
validate(config, schema="validation_schemes/config.schema.yaml")
# Update path to sampling scheme so it is uses absolute path
for method in ["sample_gtdb", "sample_ncbi"]:
    if method in config:
        config[method]["sampling_scheme"] = os.path.abspath(config[method]["sampling_scheme"])

if "required" in config:
    if config["required"] != '':
        config["required"] = os.path.abspath(config["required"])

# Set workdir
workdir: config['workdir']

# Include rules
include: "rules/commons.smk"
include: "rules/download_gtdb_data.smk"
include: "rules/download_ncbi_data.smk"
if config["method"] in ["sample_gtdb", "prune_gtdb"]:
    include: "rules/gtdb_taxonomy_phylogeny.smk"
include: "rules/ncbi_taxonomy.smk"
include: "rules/download_sampled_data.smk"

# Generate input
rule all:
    input: all_input
